### ISSUE TITLE
Configure Travis to run tests

### ISSUE THREAD

**Issue by ftomassetti** [lu-zero/plaid#62]
- [ ] configure Travis
 - [ ] add badge in the README

**Comment by ftomassetti** [comment]
There is an issue: currently we have Github integration which requires secret data. We could use this http://docs.travis-ci.com/user/encrypting-files/ but it would not work for PRs :(

**Comment by lu-zero** [comment]
It is optional since https://github.com/lu-zero/plaid/commit/d924426eeacf6e6914e1924f7144e0c54e799ad2

**Comment by ftomassetti** [comment]
Ok, but so this has been done from what I see. Closing.
